timezone: America/New_York
encoding: utf-8
baseurl: https://susanbpilates.com/

site_title: 'Susan B: Pilates'
origin: https://susanbpilates.com
cssdir: css/
imgdir: img/

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - vendor
  - README.md
  - Gemfile
  - CNAME
  - .travis.yml
  - LICENSE

defaults:
  - scope:
      path: ''
    values:
      title_delimiter: ' - '
      opengraph_type: website
      opengraph_description: 'Local pilates instructor Susan Buonopane.'
      opengraph_image: opengraph.png
  - scope:
      path: ''
      type: pages
    values:
      layout: page
  - scope:
      path: ''
      type: posts
    values:
      layout: post
  - scope:
      path: ''
      type: drafts
    values:
      layout: draft